blank_issues_enabled: false
contact_links:
  - name: 📖 问题反馈指南 / Troubleshooting Guide
    url: https://github.com/MaaEnd/MaaEnd/blob/v2/docs/zh_cn/users/troubleshooting.md
    about: 提交 Issue 前请先阅读此文档 / Please read this guide before submitting an issue
  - name: 🐧 用户 QQ 群 / User QQ Group (1062010346)
    url: https://qm.qq.com/q/Ui2ufchIIe
    about: 畅聊使用心得、提出建议等 / Chat about usage, share ideas, etc.
  - name: 🐧 开发 QQ 群 / Dev QQ Group (1072587329)
    url: https://qm.qq.com/q/EyirQpBiW4
    about: 干活群，欢迎加入一起开发，但不受理用户问题 / Development discussions only
